import Image from "next/image";
import styles from "./page.module.css";
import MeetupList from "@/components/meetups/MeetupList";
import Layout from "@/components/layout/Layout";
import Head from "next/head";

const getMeetupHandler = async () => {
  try {
    const response = await fetch("http://localhost:3000/api/posts");
    const data = await response.json();
    if (data.success) {
      return data.result;
    }
    throw new Error("Data fetch was not successful");
  } catch (error) {
    console.error("Error fetching meetups:", error);
  }
};
export default async function Home(props) {
  const meetups = await getMeetupHandler();
  return (
    <>
      <Layout>
        <Head>
          <title>Monuments</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <MeetupList meetups={meetups} />
      </Layout>
    </>
  );
}
